[Settings]
# LogLevel = "debug"
LogLevel = "info"
UseAuth = false

[CtiAPI]
Scheme = "ws"
Path = "/ws"
Host = "192.168.223.50"
Port = "8098"

[HttpAPI]
Scheme = "http"
Host = "localhost"
Port = "9595"
